In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier

In [33]:
# Load the dataset
from google.colab import files
uploaded = files.upload()

Saving Zoo.csv to Zoo (1).csv


In [34]:
df = pd.read_csv('Zoo.csv')

In [35]:
# Basic info and checking missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal name  101 non-null    object
 1   hair         101 non-null    int64 
 2   feathers     101 non-null    int64 
 3   eggs         101 non-null    int64 
 4   milk         101 non-null    int64 
 5   airborne     101 non-null    int64 
 6   aquatic      101 non-null    int64 
 7   predator     101 non-null    int64 
 8   toothed      101 non-null    int64 
 9   backbone     101 non-null    int64 
 10  breathes     101 non-null    int64 
 11  venomous     101 non-null    int64 
 12  fins         101 non-null    int64 
 13  legs         101 non-null    int64 
 14  tail         101 non-null    int64 
 15  domestic     101 non-null    int64 
 16  catsize      101 non-null    int64 
 17  type         101 non-null    int64 
dtypes: int64(17), object(1)
memory usage: 14.3+ KB


In [36]:
df.isnull().sum()

animal name    0
hair           0
feathers       0
eggs           0
milk           0
airborne       0
aquatic        0
predator       0
toothed        0
backbone       0
breathes       0
venomous       0
fins           0
legs           0
tail           0
domestic       0
catsize        0
type           0
dtype: int64

In [37]:
# Data Preprocessing
df.head()

animal name  hair  feathers  eggs  milk  airborne  ...  fins  legs  tail  domestic  catsize  type
0    aardvark     1         0     0     1         0  ...     0     4     0         0        1     1
1    antelope     1         0     0     1         0  ...     0     4     1         0        1     1
2        bass     0         0     1     0         0  ...     1     0     1         0        0     4
3        bear     1         0     0     1         0  ...     0     4     0         0        1     1
4        boar     1         0     0     1         0  ...     0     4     1         0        1     1

[5 rows x 18 columns]

In [38]:
df.drop('animal name', axis=1, inplace=True)

In [39]:
df.head()

hair  feathers  eggs  milk  airborne  aquatic  ...  fins  legs  tail  domestic  catsize  type
0     1         0     0     1         0        0  ...     0     4     0         0        1     1
1     1         0     0     1         0        0  ...     0     4     1         0        1     1
2     0         0     1     0         0        1  ...     1     0     1         0        0     4
3     1         0     0     1         0        0  ...     0     4     0         0        1     1
4     1         0     0     1         0        0  ...     0     4     1         0        1     1

[5 rows x 17 columns]

In [40]:
# Splitting features and target
X = df.drop('type', axis=1)    # Features
y = df['type'] # Target variable

In [41]:
# Standardizing features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


In [43]:
# Grid search for algorithm tunnig
import numpy
n_neighbors = numpy.array(range(1,21))
param_grid = dict(n_neighbors=n_neighbors)
param_grid

{'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])}

In [44]:
# Step 4: Hyperparameter Tuning with GridSearchCV
param_grid = {'n_neighbors': range(1, 21), 'metric': ['euclidean', 'manhattan', 'minkowski']}
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': range(1, 21)},
             scoring='accuracy')

In [45]:
# Best parameters and model
best_k = grid_search.best_params_['n_neighbors']
best_metric = grid_search.best_params_['metric']
print(f"Best K: {best_k}, Best Metric: {best_metric}")

Best K: 1, Best Metric: euclidean


In [46]:
# Implementing Best KNN Model
knn = KNeighborsClassifier(n_neighbors=best_k, metric=best_metric)
knn.fit(X_train, y_train)


KNeighborsClassifier(metric='euclidean', n_neighbors=1)

In [47]:
# Predictions
y_pred = knn.predict(X_test)


In [48]:
# Model Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         1

    accuracy                           1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21

Confusion Matrix:
 [[12  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  1]]


In [49]:
# Visualizing Decision Boundaries (for 2D case, if possible)
def plot_decision_boundary(X, y, model):
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100), np.linspace(y_min, y_max, 100))
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, alpha=0.3)
    sns.scatterplot(x=X[:, 0], y=X[:, 1], hue=y, palette='coolwarm', edgecolor='k')
    plt.show()

In [50]:
# Visualizing only if dataset has exactly 2 features
if X_train.shape[1] == 2:
    plot_decision_boundary(X_train, y_train, knn)